name: Bug Report
description: Report a problem with AgentGuard
labels: ["type:bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Describe the bug clearly and concisely.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Install agentguard47
        2. Run this code: ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include error messages or tracebacks.
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.11"
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: AgentGuard version
      placeholder: "1.2.0"
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Agent framework
      options:
        - None / standalone
        - LangChain
        - LangGraph
        - CrewAI
        - Other
    validations:
      required: true

  - type: textarea
    id: traces
    attributes:
      label: Trace output
      description: If possible, paste relevant JSONL trace lines.
      render: json
