name: Feature Request
description: Suggest a new capability for AgentGuard
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's frustrating today?
      placeholder: "When I try to ..., I can't because ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Include code examples if possible.
      placeholder: |
        ```python
        from agentguard import ...
        ```
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - SDK core (guards, tracing)
        - Integration (LangChain, LangGraph, CrewAI)
        - CLI
        - Dashboard
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and why?
    validations:
      required: false
