name: Feature Request
description: Suggest a new capability for AgentGuard
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's frustrating today?
      placeholder: "When I try to ..., I can't because ..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Include code examples if possible.
      placeholder: |
        ```python
        from agentguard import ...
        ```
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - SDK core (guards, tracing)
        - Integration (LangChain, LangGraph, CrewAI)
        - CLI
        - Dashboard
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and why?
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this is done? Be specific.
      placeholder: |
        - [ ] Guard raises exception when budget exceeds $5
        - [ ] Works with LangChain AgentGuardCallbackHandler
        - [ ] Test coverage for new code
    validations:
      required: true

  - type: dropdown
    id: roadmap
    attributes:
      label: Roadmap alignment
      description: Does this relate to an existing ops/03-ROADMAP item?
      options:
        - "Yes — existing Now/Next item"
        - "Yes — existing Later item"
        - "No — new idea"
    validations:
      required: true
