from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_OWNER = "bmdhodl"
REPO_NAME = "agent47"
OUTPUT_PATH = Path("sdk/PYPI_README.md")
README_PATH = Path("README.md")
CHANGELOG_PATH = Path("CHANGELOG.md")
PYPROJECT_PATH = Path("sdk/pyproject.toml")

GENERATED_HEADER = (
    "<!-- Generated by scripts/generate_pypi_readme.py. "
    "Edit README.md and CHANGELOG.md instead. -->"
)

LINK_TARGET_RE = re.compile(r"(?<=\])\(([^)]+)\)")
GITHUB_ABSOLUTE_LINK_RE = re.compile(
    rf"https://github\.com/{REPO_OWNER}/{REPO_NAME}/(?P<mode>blob|tree)/main/(?P<path>[^)#]+)"
)
COLAB_ABSOLUTE_LINK_RE = re.compile(
    rf"https://colab\.research\.google\.com/github/{REPO_OWNER}/{REPO_NAME}/blob/main/(?P<path>[^)#]+)"
)
UNRELEASED_PATHS = {
    "docs/competitive/agent-security-stack.md",
    "docs/examples/coding-agent-review-loop-incident.md",
    "docs/examples/proof-gallery.md",
    "docs/guards/budget-aware-escalation.md",
    "docs/guides/dashboard-contract.md",
    "docs/guides/decision-tracing.md",
    "docs/guides/managed-agent-sessions.md",
    "docs/release/trusted-publishing.md",
    "examples/sticky_agent_proof.py",
}


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _load_version(repo_root: Path) -> str:
    pyproject_text = (repo_root / PYPROJECT_PATH).read_text(encoding="utf-8")
    project_section = re.search(
        r"^\[project\]\s*(?P<body>.*?)(?=^\[|\Z)",
        pyproject_text,
        flags=re.MULTILINE | re.DOTALL,
    )
    if project_section is None:
        raise ValueError("Could not find [project] section in sdk/pyproject.toml")

    version_match = re.search(
        r'^version\s*=\s*"(?P<version>[^"]+)"\s*$',
        project_section.group("body"),
        flags=re.MULTILINE,
    )
    if version_match is None:
        raise ValueError("Could not find project.version in sdk/pyproject.toml")
    return version_match.group("version")


def _ref_for_repo_path(version: str, normalized_path: str) -> str:
    if normalized_path in UNRELEASED_PATHS:
        return "main"
    return f"v{version}"


def _github_url(version: str, relative_target: str, repo_root: Path) -> str:
    if "#" in relative_target:
        path_part, anchor_fragment = relative_target.split("#", 1)
        anchor_fragment = f"#{anchor_fragment}"
    else:
        path_part = relative_target
        anchor_fragment = ""
    candidate = (repo_root / path_part).resolve()
    try:
        relative = candidate.relative_to(repo_root.resolve())
    except ValueError:
        return relative_target

    path_mode = "tree" if candidate.exists() and candidate.is_dir() else "blob"
    normalized = "/".join(relative.parts)
    ref = _ref_for_repo_path(version, normalized)
    return f"https://github.com/{REPO_OWNER}/{REPO_NAME}/{path_mode}/{ref}/{normalized}{anchor_fragment}"


def rewrite_relative_links(markdown: str, version: str, repo_root: Path) -> str:
    def replace(match: re.Match[str]) -> str:
        target = match.group(1)
        stripped = target.strip()
        if (
            "://" in stripped
            or stripped.startswith(("mailto:", "#", "data:"))
        ):
            return match.group(0)
        return f"({_github_url(version, stripped, repo_root)})"

    return LINK_TARGET_RE.sub(replace, markdown)


def rewrite_repo_absolute_links(markdown: str, version: str, repo_root: Path) -> str:
    def replace_repo(match: re.Match[str]) -> str:
        normalized_path = match.group("path")
        mode = match.group("mode")
        ref = _ref_for_repo_path(version, normalized_path)
        return f"https://github.com/{REPO_OWNER}/{REPO_NAME}/{mode}/{ref}/{normalized_path}"

    def replace_colab(match: re.Match[str]) -> str:
        normalized_path = match.group("path")
        ref = _ref_for_repo_path(version, normalized_path)
        return (
            f"https://colab.research.google.com/github/{REPO_OWNER}/{REPO_NAME}/blob/"
            f"{ref}/{normalized_path}"
        )

    markdown = GITHUB_ABSOLUTE_LINK_RE.sub(replace_repo, markdown)
    return COLAB_ABSOLUTE_LINK_RE.sub(replace_colab, markdown)


def extract_release_notes(changelog: str, version: str) -> str:
    heading = f"## {version}"
    start = changelog.find(heading)
    if start == -1:
        raise ValueError(f"Could not find changelog section for {version}")

    remainder = changelog[start + len(heading):]
    next_heading = remainder.find("\n## ")
    section = remainder[:next_heading] if next_heading != -1 else remainder
    section = section.strip()
    if not section:
        raise ValueError(f"Changelog section for {version} is empty")
    return section


def build_pypi_readme(repo_root: Path) -> str:
    version = _load_version(repo_root)
    readme = (repo_root / README_PATH).read_text(encoding="utf-8").strip()
    changelog = (repo_root / CHANGELOG_PATH).read_text(encoding="utf-8")
    release_notes = extract_release_notes(changelog, version)

    rewritten_readme = rewrite_relative_links(readme, version, repo_root)
    rewritten_readme = rewrite_repo_absolute_links(rewritten_readme, version, repo_root)
    rewritten_changelog_link = _github_url(version, str(CHANGELOG_PATH).replace("\\", "/"), repo_root)

    parts = [
        GENERATED_HEADER,
        "",
        rewritten_readme,
        "",
        f"## Latest Release Notes ({version})",
        "",
        release_notes,
        "",
        f"Full changelog: [CHANGELOG.md]({rewritten_changelog_link})",
        "",
    ]
    return "\n".join(parts)


def write_output(repo_root: Path, output_path: Path) -> int:
    content = build_pypi_readme(repo_root)
    target = repo_root / output_path
    target.write_text(content, encoding="utf-8", newline="\n")
    return 0


def check_output(repo_root: Path, output_path: Path) -> int:
    expected = build_pypi_readme(repo_root)
    target = repo_root / output_path
    actual = target.read_text(encoding="utf-8") if target.exists() else ""
    if actual != expected:
        sys.stderr.write(
            f"{output_path} is out of date. Run `python scripts/generate_pypi_readme.py --write`.\n"
        )
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the PyPI README from repo docs.")
    parser.add_argument("--write", action="store_true", help="Write the generated README to disk.")
    parser.add_argument("--check", action="store_true", help="Fail if the generated README is out of date.")
    parser.add_argument("--stdout", action="store_true", help="Print the generated README to stdout.")
    parser.add_argument(
        "--output",
        default=str(OUTPUT_PATH),
        help="Path to the generated README, relative to the repo root.",
    )
    args = parser.parse_args(argv)

    repo_root = _repo_root()
    output_path = Path(args.output)

    if args.check:
        return check_output(repo_root, output_path)
    if args.write:
        return write_output(repo_root, output_path)
    if args.stdout:
        sys.stdout.write(build_pypi_readme(repo_root))
        return 0

    parser.error("Choose one of --write, --check, or --stdout.")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
